spring.application.name=productservice

# Server Port
server.port=8084

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/product
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Kafka broker
spring.kafka.bootstrap-servers=localhost:9092

# Consumer
spring.kafka.consumer.group-id=product-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Allow event class
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Ignore producer class header
spring.kafka.consumer.properties.spring.json.use.type.headers=false

spring.kafka.consumer.properties.spring.json.value.default.type=com.productservice.dto.OrderCreatedEvent

# Remove type header from message
spring.kafka.consumer.properties.spring.json.remove.type.headers=true

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer